import React, { createContext, useContext, useState, useCallback } from "react";

const translations = {
  en: {
    // Landing
    hero_title: "The Sovereign AI Control Plane",
    hero_subtitle: "Govern AI agents, workflows and models before compliance, security and audit become a problem. Built for Europe's most regulated industries.",
    hero_cta: "Enter Control Plane",
    hero_cta_secondary: "Explore Features",
    nav_features: "Features",
    nav_clients: "Clients",
    nav_compliance: "Compliance",
    nav_dashboard: "Dashboard",
    // Features
    features_title: "Enterprise AI Governance",
    features_subtitle: "Complete control over every AI agent in your organization",
    feat_policy: "Policy Engine",
    feat_policy_desc: "Define what AI agents can do, where, how, and why. Granular rule-based governance with real-time enforcement.",
    feat_audit: "Audit Trail",
    feat_audit_desc: "Complete traceability of every AI action. Explainability logs, decision chains, and immutable records.",
    feat_compliance: "Compliance Monitor",
    feat_compliance_desc: "AI Act, GDPR, ISO 27001, ISO 42001, DORA, NIS2 — track compliance status in real-time.",
    feat_integration: "Enterprise Integration",
    feat_integration_desc: "Seamless connection with IAM, SIEM, ServiceNow, CMDB, and your existing security stack.",
    feat_risk: "Risk Classification",
    feat_risk_desc: "Automatic risk assessment aligned with EU AI Act categories. From minimal to unacceptable risk.",
    feat_ai: "AI Assistant",
    feat_ai_desc: "GPT-powered compliance advisor. Ask questions about regulations, get actionable guidance instantly.",
    // Clients
    clients_title: "Built for Regulated Industries",
    clients_subtitle: "Designed for organizations where compliance is not optional",
    client_pa: "Public Administration",
    client_bank: "Banking & Finance",
    client_insurance: "Insurance",
    client_health: "Healthcare",
    client_energy: "Energy & Utilities",
    client_telecom: "Telecommunications",
    // Dashboard
    sidebar_overview: "Overview",
    sidebar_agents: "AI Agents",
    sidebar_policies: "Policies",
    sidebar_audit: "Audit Trail",
    sidebar_compliance: "Compliance",
    sidebar_assistant: "ARIA",
    // Overview
    overview_title: "Control Plane Overview",
    total_agents: "Total Agents",
    active_agents: "Active",
    total_policies: "Policies",
    active_policies: "Active",
    audit_events: "Audit Events",
    blocked_events: "Blocked",
    compliance_score: "Compliance Score",
    recent_activity: "Recent Activity",
    risk_distribution: "Risk Distribution",
    // Agents
    agents_title: "AI Agents Registry",
    agents_subtitle: "Manage and govern all AI agents in your organization",
    new_agent: "New Agent",
    agent_name: "Agent Name",
    agent_description: "Description",
    agent_model: "Model Type",
    agent_risk: "Risk Level",
    agent_status: "Status",
    agent_owner: "Owner",
    agent_actions: "Allowed Actions",
    agent_restricted: "Restricted Domains",
    agent_data_class: "Data Classification",
    // Policies
    policies_title: "Policy Engine",
    policies_subtitle: "Define governance rules for AI agents",
    new_policy: "New Policy",
    policy_name: "Policy Name",
    policy_description: "Description",
    policy_type: "Rule Type",
    policy_severity: "Severity",
    policy_regulation: "Regulation",
    policy_enforcement: "Enforcement",
    policy_conditions: "Conditions",
    policy_actions: "Actions",
    // Audit
    audit_title: "Audit Trail",
    audit_subtitle: "Complete traceability of all AI operations",
    audit_search: "Search logs...",
    audit_filter_outcome: "Filter by outcome",
    audit_filter_risk: "Filter by risk",
    // Compliance
    compliance_title: "Compliance Monitor",
    compliance_subtitle: "Real-time regulatory compliance tracking",
    // Assistant
    assistant_title: "Compliance AI Assistant",
    assistant_subtitle: "Ask questions about EU AI Act, GDPR, ISO standards, and AI governance",
    assistant_placeholder: "Ask about compliance, regulations, governance...",
    // Common
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    search: "Search",
    filter: "Filter",
    all: "All",
    loading: "Loading...",
    no_data: "No data available",
    actions: "Actions",
    status: "Status",
    back_to_site: "Back to Site",
    language: "Language",
  },
  it: {
    hero_title: "Il Control Plane Sovrano per l'AI",
    hero_subtitle: "Governa agenti AI, workflow e modelli prima che compliance, sicurezza e audit diventino un problema. Progettato per i settori piu regolamentati d'Europa.",
    hero_cta: "Accedi al Control Plane",
    hero_cta_secondary: "Esplora le Funzionalita",
    nav_features: "Funzionalita",
    nav_clients: "Clienti",
    nav_compliance: "Compliance",
    nav_dashboard: "Dashboard",
    features_title: "Governance AI Enterprise",
    features_subtitle: "Controllo completo su ogni agente AI nella tua organizzazione",
    feat_policy: "Motore di Policy",
    feat_policy_desc: "Definisci cosa possono fare gli agenti AI, dove, come e perche. Governance granulare basata su regole con applicazione in tempo reale.",
    feat_audit: "Traccia di Audit",
    feat_audit_desc: "Tracciabilita completa di ogni azione AI. Log di spiegabilita, catene decisionali e registrazioni immutabili.",
    feat_compliance: "Monitor Compliance",
    feat_compliance_desc: "AI Act, GDPR, ISO 27001, ISO 42001, DORA, NIS2 — monitora lo stato di conformita in tempo reale.",
    feat_integration: "Integrazione Enterprise",
    feat_integration_desc: "Connessione fluida con IAM, SIEM, ServiceNow, CMDB e il tuo stack di sicurezza esistente.",
    feat_risk: "Classificazione del Rischio",
    feat_risk_desc: "Valutazione automatica del rischio allineata alle categorie dell'EU AI Act. Dal rischio minimo a quello inaccettabile.",
    feat_ai: "Assistente AI",
    feat_ai_desc: "Consulente compliance alimentato da GPT. Fai domande sulle normative, ottieni indicazioni operative immediatamente.",
    clients_title: "Progettato per Settori Regolamentati",
    clients_subtitle: "Pensato per organizzazioni dove la compliance non e opzionale",
    client_pa: "Pubblica Amministrazione",
    client_bank: "Banche e Finanza",
    client_insurance: "Assicurazioni",
    client_health: "Sanita",
    client_energy: "Energia e Utilities",
    client_telecom: "Telecomunicazioni",
    sidebar_overview: "Panoramica",
    sidebar_agents: "Agenti AI",
    sidebar_policies: "Policy",
    sidebar_audit: "Traccia Audit",
    sidebar_compliance: "Compliance",
    sidebar_assistant: "ARIA",
    overview_title: "Panoramica del Control Plane",
    total_agents: "Agenti Totali",
    active_agents: "Attivi",
    total_policies: "Policy",
    active_policies: "Attive",
    audit_events: "Eventi Audit",
    blocked_events: "Bloccati",
    compliance_score: "Punteggio Compliance",
    recent_activity: "Attivita Recente",
    risk_distribution: "Distribuzione Rischio",
    agents_title: "Registro Agenti AI",
    agents_subtitle: "Gestisci e governa tutti gli agenti AI della tua organizzazione",
    new_agent: "Nuovo Agente",
    agent_name: "Nome Agente",
    agent_description: "Descrizione",
    agent_model: "Tipo Modello",
    agent_risk: "Livello Rischio",
    agent_status: "Stato",
    agent_owner: "Responsabile",
    agent_actions: "Azioni Consentite",
    agent_restricted: "Domini Ristretti",
    agent_data_class: "Classificazione Dati",
    policies_title: "Motore di Policy",
    policies_subtitle: "Definisci regole di governance per gli agenti AI",
    new_policy: "Nuova Policy",
    policy_name: "Nome Policy",
    policy_description: "Descrizione",
    policy_type: "Tipo Regola",
    policy_severity: "Severita",
    policy_regulation: "Normativa",
    policy_enforcement: "Applicazione",
    policy_conditions: "Condizioni",
    policy_actions: "Azioni",
    audit_title: "Traccia di Audit",
    audit_subtitle: "Tracciabilita completa di tutte le operazioni AI",
    audit_search: "Cerca nei log...",
    audit_filter_outcome: "Filtra per esito",
    audit_filter_risk: "Filtra per rischio",
    compliance_title: "Monitor Compliance",
    compliance_subtitle: "Monitoraggio conformita normativa in tempo reale",
    assistant_title: "Assistente AI Compliance",
    assistant_subtitle: "Fai domande su EU AI Act, GDPR, standard ISO e governance AI",
    assistant_placeholder: "Chiedi di compliance, normative, governance...",
    save: "Salva",
    cancel: "Annulla",
    delete: "Elimina",
    edit: "Modifica",
    create: "Crea",
    search: "Cerca",
    filter: "Filtra",
    all: "Tutti",
    loading: "Caricamento...",
    no_data: "Nessun dato disponibile",
    actions: "Azioni",
    status: "Stato",
    back_to_site: "Torna al Sito",
    language: "Lingua",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState("en");

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations.en[key] || key;
  }, [lang]);

  const toggleLang = useCallback(() => {
    setLang(prev => prev === "en" ? "it" : "en");
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
